### ISSUE TITLE
Data JSON parsing

### ISSUE THREAD

**Issue by Sairyss** [Software-On-The-Road/agendash-v2#14]
Great job on the dashboard, I want to use it for my project but I have one issue that prevents me from doint it:
While creating job and passing data json, for example:
![изображение](https://user-images.githubusercontent.com/42232541/82658054-ad652a00-9c26-11ea-930b-7d14ad582769.png)

In database this json is saved like this:
`"data" : "{\n   \"test\":\"test\",\n   \"test2\":\"test2\"\n}"`
It saves all the new lines as "\n", and if there are tabs it's gonna save those aswell like "\t", so the job doesn't work like this and I have to parse inputs which adds mess to my code.
This doesn't happen in original agendash, passing same json saves it normally

**Comment by santiq** [comment]
Hi @Sairyss 
Thanks for taking the time to test this feature. 

I'll send a fix for it this weekend.
